pin_lvttl_signal AC23 de1_cl_inputs_status__sr_data
pin_lvttl_signal AE24 de1_cl_inputs_status__left_rotary__direction_pin
pin_lvttl_signal AD24 de1_cl_inputs_status__left_rotary__transition_pin
pin_lvttl_signal AB21 de1_cl_inputs_status__right_rotary__direction_pin
pin_lvttl_signal AB17 de1_cl_inputs_status__right_rotary__transition_pin
pin_lvttl_signal AF25 de1_cl_inputs_control__sr_clock
pin_lvttl_signal AE23 de1_cl_inputs_control__sr_shift
pin_lvttl_signal AG25 de1_cl_led_data_pin
pin_lvttl_signal AK27 de1_cl_lcd__clock
pin_lvttl_signal AJ27 de1_cl_lcd__vsync_n
pin_lvttl_signal AK29 de1_cl_lcd__hsync_n
pin_lvttl_signal AH27 de1_cl_lcd__display_enable
pin_lvttl_signal {AC22 AA20 AD21 AE22 AF23 AF24} de1_cl_lcd__red
pin_lvttl_signal {AG22 AH22 AJ22 AK22 AH23 AK23 AG23} de1_cl_lcd__green
pin_lvttl_signal {AK24 AJ24 AJ25 AH25 AK26 AJ26} de1_cl_lcd__blue
pin_lvttl_signal AA21 de1_cl_lcd__backlight


